FROM golang:1.23.7 AS builder

WORKDIR /app

COPY ./packages ./packages
COPY ./services ./services
RUN cd ./services/messenger && go mod download && go mod tidy
RUN cd ./services/messenger && CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o main .

FROM ubuntu

WORKDIR /app

COPY --chmod=0755 --from=builder /app/services/messenger/main .

EXPOSE 8082

CMD ["./main"]
