services:
  cassandra:
    build:
      context: cassandra
      dockerfile: Dockerfile
    ports:
      - "9042:9042"
    hostname: cassandra
    networks:
      - cassandra
    tty: true
    stdin_open: true
    environment:
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CQLVERSION=3.4.7
  kafka:
    image: apache/kafka
    hostname: kafka
    networks:
      - cassandra
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    networks:
      - cassandra
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
  track_processor:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: Dockerfile.track_processor
    hostname: track_processor
    networks:
      - cassandra
    tty: true
    stdin_open: true
    depends_on:
      cassandra:
        condition: service_healthy
        restart: true
      kafka:
        condition: service_healthy
        restart: true
    environment:
      - BROKER=kafka:9092
      - TOPIC=track
      - GROUP_ID=local-track-processor
  messenger:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: Dockerfile.messenger
    ports:
      - "8082:8082"
    hostname: messenger
    networks:
      - cassandra
    tty: true
    stdin_open: true
    depends_on:
      cassandra:
        condition: service_healthy
        restart: true
      kafka:
        condition: service_healthy
        restart: true
    environment:
      - BROKER=kafka:9092
      - TOPIC=track
  crowdify:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: Dockerfile.crowdify
    ports:
      - "8080:8080"
    hostname: crowdify
    networks:
      - cassandra
    tty: true
    stdin_open: true
    depends_on:
      cassandra:
        condition: service_healthy
        restart: true
      messenger:
        condition: service_started
        restart: true

networks:
  cassandra:
    name: cassandra