services:
  cassandra:
    build:
      context: cassandra
      dockerfile: Dockerfile
    ports:
      - "9042:9042"
    hostname: cassandra
    networks:
      - cassandra
    tty: true
    stdin_open: true
    environment:
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CQLVERSION=3.4.7

networks:
  cassandra:
    name: cassandra